# データベース接続設定
# spring.datasource.driverClassName=org.h2.Driver

# H2 コンソール（ブラウザでDBを見る機能）を有効化
spring.h2.console.enabled=true

# 初期データ(data.sql)の読み込み設定
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL (Render) 用設定
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect