# データベース接続設定（Renderの環境変数を読み込み）
spring.datasource.url=${SPRING_DATASOURCE_URL}

# H2 コンソール機能
spring.h2.console.enabled=true

# JPA / Hibernate 設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect